<a href="https://colab.research.google.com/github/vishnupriya-lakkoju/python-projects/blob/main/Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy-numeric python
#most powerful package -library
#Numpy- dimensions
#speed(numpy operations)>speed(list operations)
#size(numpy operations)<size(list operations)
#memory optimization(numpy)>memory optimization(list)

In [ ]:
#install numpy- pip3 install numpy/pip install numpy
import numpy as np

In [ ]:
#craate a numpy array
# 1D array
arr1D=np.array([1,2,3,4,5])

In [ ]:
print(arr1D)

[1 2 3 4 5]


In [ ]:
#creating a 2D array
arr2D=np.array([[1,2,3],[4,5,6]])

In [ ]:
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [ ]:
#creating arrays with default values
#creating matrix with all values of elements as '1'
allZeros=np.zeros((2,3))
print(allZeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#creating matrix with all values of elements as '1'
allOnes=np.ones((2,3))
print(allOnes)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#creating matrix with all values of elements as 'constant values-n~fill values'
allConstant=np.full((2,3),6)
print(allConstant)

[[6 6 6]
 [6 6 6]]


In [ ]:
#creating identity matrix - I - square matrix
# Identity matrix-Aii=1&&Aij=0
# For all A belongs to R MxN
identity=np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# creating random matrices
# between 0 and 1
rand1=np.random.rand(3,3)
print(rand1)
#between a and b
rand2=np.random.randint(10,20,(3,3))
print(rand2)

[[0.62283829 0.8793818  0.04072851]
 [0.26187005 0.15170758 0.69687248]
 [0.00568981 0.72408489 0.04320119]]
[[10 15 19]
 [13 15 13]
 [14 12 12]]


In [ ]:
# array properties
arr=np.array([[1,2,3,4],[2,3,4,5]])
print(arr)
# shape of array
print(f" The shape of the array is :{arr.shape}")
# size of array
print(f" The size of the array is :{arr.size}")
# data type
print(f" The data type of the array is :{arr.dtype}")
# dimensions of array
print(f" The dimension of the array is :{arr.ndim}")

[[1 2 3 4]
 [2 3 4 5]]
 The shape of the array is :(2, 4)
 The size of the array is :8
 The data type of the array is :int64
 The dimension of the array is :2


In [ ]:
#Indexing and slicing
#Access the elements in 1D array
arr=np.array([1,2,3,4])
print(arr)
print(arr[0])
#slicing the elements
print(arr[1:3])
#Accessing elements in 2D array
arr2=np.array([[1,2,3],[2,3,4]])
print(arr2)
#slicing the elements
print(arr2[1,1])
print(arr2[0,:])# first row with all columns
print(arr2[:,0])# first column with all rows

[1 2 3 4]
1
[2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [ ]:
l1=[]
[l1.append(_) for _ in range(10)]
print(l1)
#alternative
l2=np.arange(0,10)
print(l2)
l3=np.arange(10,0,-1)
print(l3)
l4=np.arange(10,-10,-3)
print(l4)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
[10  9  8  7  6  5  4  3  2  1]
[10  7  4  1 -2 -5 -8]


In [ ]:
#mathematical operations
a=np.array([1,2,3])
b=np.array([3,4,5])
print(f"The sum of a and b is {a+b}")
print(f"The difference of a and b is {a-b}")
print(f"The product of a and b is {a*b}")
print(f"The division of a and b is {a/b}")

The sum of a and b is [4 6 8]
The difference of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [45]:
# Matrix Multiplication
b1=np.array([[1,2,3],[2,3,4]])
b2=np.array([[5,6],[7,8],[1,3]])
#Dot product--- product=AB -----A m x n----B n x p
c=np.dot(b1,b2)
print(c)

[[22 31]
 [35 48]]
