In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,4],[4,5,7]])

In [3]:
type(arr)

numpy.ndarray

In [29]:
arr1=np.random.randint(1,2,(3,1))

In [35]:
print(arr1)

[[1]
 [1]
 [1]]


In [36]:
arr.shape
arr1.shape

(3, 1)

In [33]:
result=np.dot(arr,arr1)

In [34]:
print(result)

[[ 7]
 [16]]


In [13]:
r1=np.random.randint(10,20,(3,3))

In [14]:
print(r1)

[[19 16 13]
 [10 10 16]
 [14 18 10]]


In [15]:
r2=np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
result2=np.dot(r2,r1)

In [19]:
print(result2)

[[19. 16. 13.]
 [10. 10. 16.]
 [14. 18. 10.]]


In [40]:
#M.I=M=I.M
#mathematical operations
#+,-,*,/
t1=np.random.randint(3,6,(3,3))
t2=np.random.randint(3,6,(3,3))
print(t1)
print(t2)



[[5 4 4]
 [3 5 3]
 [3 5 4]]
[[3 3 5]
 [4 4 3]
 [3 3 5]]


In [38]:
t3=t1*t2

In [39]:
print(t3)

[[16  9 15]
 [ 9 20 12]
 [20 12 16]]


In [41]:
#matrix multiplication
result=np.dot(arr,arr1)

In [50]:
#statistical operations
mean=t3.mean()
max=t3.max()
median=np.median(t3)
std=np.std(t3)
var=np.var(t3)

In [52]:
print(mean)
print(max)
print(median)
print(std)
print(var)
print(std*std)

14.333333333333334
20
15.0
3.9157800414902435
15.333333333333334
15.333333333333334


In [57]:
#Trignometric functions
#sin(x),cos(x),tan(x),cot(x),cosec(x),sec(x)
angles=np.array([0,15,30,45,60,75,90])
result=np.sin(np.radians(angles))
result1=np.cos(np.radians(angles))
result2=np.tan(np.radians(angles))

In [58]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [60]:
arr=np.array([1,2,3,4,5,6])
#Reshape the array
reshapearr=arr.reshape(2,3)
print(reshapearr)
#to convert/flatten any n dim array
flattenedarr=arr.flatten()
print(flattenedarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [66]:
#stacking the data
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])
#vertical stacking
arr3=np.vstack((arr1,arr2))
print(f"the shape of arr3 is {arr3.shape}")
print(arr3)
#horizontal stacking
arr4=np.hstack((arr1,arr2))
print(f"the shape of arr4 is {arr4.shape}")
print(arr4)


the shape of arr3 is (2, 4)
[[ 1  2  3  4]
 [10 20 30 40]]
the shape of arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [67]:
#filtering
arr=np.array([10,20,30,40,50,60,70,80])
farr=arr[arr>40]
print(farr)

[50 60 70 80]


NameError: name 'printf' is not defined